### ISSUE TITLE
Scripts error and can't buy car 

### ISSUE THREAD

**Issue by 0411447** [KamuiKody/k-dealership#3]
Error code "object is not a string" can't buy vehicle or interact with it after it has been placed. 
![Screenshot 2022-09-14 090708](https://user-images.githubusercontent.com/78282873/190098069-ab589ac5-c6cb-40c8-ba3c-8a8ee7ee0c8d.png)

**Comment by Botman64** [comment]
please double check your config to your sql and be sure that everything is inserted properly  and that the config matches the database table.
