### ISSUE TITLE
No spawn on login

### ISSUE THREAD

**Issue by ElusionPDX** [KamuiKody/k-dealership#5]
So everything seems to be working can buy the place, see the menu but when i try to order a car the list is empty.

**Comment by Botman64** [comment]
do u have money to buy cars?

**Comment by ElusionPDX** [comment]
Nope :D cuz i thought it would pull from the dealer money. my bad

**Comment by Botman64** [comment]
no problem haha

**Comment by ElusionPDX** [comment]
Hey boss man, Did you just not add a way for the dealership cars on the floor to show on a login?
